version: '3'

services:
  redis:
    image: redis
    ports:
      - 6380:6379

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: nawanolza
      MYSQL_ROOT_PASSWORD: nawanolza1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    restart: always
    volumes:
      - ../db/docker-volume-mysql:/var/lib/mysql